@startuml
abstract class DB <<parent>>{
  -private
  +public
  #protected
  test()
}
DB <|-- User
DB <|-- Product

class User{

}
object user {
  name = "Dummy"
  id = 123
}
class Product{

}


@enduml
