@startsalt
{
  Brickler Family Tree
  {T
    + Zenon Brickler (?) | <color: gold>Patriarch</color>
    ++ Alexander Brickler (Alice Lucas-Brickler)
      +++ Alexander Brickler II
        ++++ Celeste Brickler
          +++++ Adam
        ++++ Alexander Brickler III
          +++++ Alexander Brickler IV
          +++++ David P Brickler
        ++++ David
          +++++ Jake
          +++++ Maya
          +++++ Preston
        ++++ Michael
      +++ Alice Brickler

    ++ Frank Brickler
    ++ Phillip
    ++ Dan
    ++ Jim
    ++ Wallace
  }
  --
  Anderson Family Tree
  {T
    + George W. Anderson (1830s, Nancy Beale of John "Fiat" Beal of James Paxton ) | <color: gold>Patriarch</color>
    ++ Ernest (1864)
    ++ John(1871)
    ++ George II (1872)
    ++ Nora (1874)
    ++ Sylvestor/Sylvester (1877) (Virginia Gunn)
    +++ Earl L. (10/22/1901)
		+++ Clyde S. (2/10/1903 - 1922)
		+++ James K. (12/06/1904) & Irene Johnson (sister to Celeste)
    ++++ (?)
    ++++ Marion & Walter Wilson
    +++++ Walter James Jr. (3/10/54)
    +++++ Allen Wilson (4/10/56) & Eva Marda
    ++++ James II
		+++ Russell L. Anderson (1/12/1906) & Celeste Etta Johnson (6/25/1901)
    ++++ Dr. Russell Lloyd Jr. (3/3/28) & Betty Douglas
    +++++ Rozlyn Flood (6/10/51) & Larry
    ++++++ Jason
    ++++++ Jeremy
		++++ Mrs. Dorothy Maureen (7/6/29) Alexander D. J. Brickler
    ++++++ Celest Eileen Hart (6/25/52) & Christopher Hart
    +++++++ Adam
    ++++++ Alexander D. J. III (11/17/55) & Mildred Petty
    +++++++ Alexander D. J. IV
    +++++++ David P.
    ++++++ David L. (1/15/59) & Lynn Vatsaloo
    +++++++ Jake
    +++++++ Maya
    +++++++ Preston
		++++ Mrs. Delores (?Dolores) (2/4/32) Lucille & Robert B. Farr
    +++++ Robert B. Farr Jr.
    ++++++ Rigel
    ++++++ Lucas
    +++++ Rachel Chandler & Michael
    ++++++ Anthony
    ++++++ Alicia
    +++++ Jenilee Brockman & Martin
    ++++++ Eli
    ++++++ Rachel
		++++ Donald L. Anderson (2/4/32)
		+++ John V. (1/10/1909)
		+++ Eugene (1910)
		+++ William R. (9/15/1911)
		+++ Louise V. (8/25/1915)
    ++ Gertrude (1881)

  }
}
@endsalt
