@startuml
  rectangle "Brickler Family Tree" as B {
  actor "Zenon Brickler" as Z
  (Alexander Brickler) as (A)
  (Alexander Brickler II) as (AII)
  (Alexander Brickler III) as (AIII)
  (Alexander Brickler IV) as (AIV)

    Z -down- (A)
      (A) -down- (AII)
        (AII) -right- (D)
        (AII) -down- (Celeste)
          (Celeste) -down- (Adam)
        (AII) -down- (AIII)
          (AIII) -down- (AIV)
          (AIII) -down- (David P)
        (AII) -down- (David)
          (David) -down- (Jake)
          (David) -down- (Maya)
          (David) -down- (Pewaron)

        (AII) -down- (Michael)
    Z -down- (Frank)
    Z -down- (Phillip)
    Z -down- (Dan)
    Z -down- (Jim)
    Z -down- (Wallace)
  }

  rectangle "Anderson Family Tree" <<Anderson>> #blue {
    :George W. Anderson 1830s: as GA
    (Sylvestor - 1877 Virginia Gunn) as (S)
    (Russell L - 1906) as (R)
    (Dorothy Maureen) as (D)
    GA -- (Ernest - 1864)
    GA -- (John - 1871)
    GA -- (George II - 1872)
    GA -- (Nora - 1874)
    GA -- (S)
      (S) -- (Earl L. - 1901)
      (S) -- (Clyde - 1903)
      (S) -- (James K. - 1904)
      (S) -- (R)
        (R) -- (D)
          (D) -- (Celeste)
          (D) -- (AIII)
          (D) -- (David)
          (D) -- (Michael)
      (S) -- (John V. - 1909)
      (S) -- (Eugene - 1910)
      (S) -- (William R. 1911)
      (S) -- (Louise V. 1915)
  }
@enduml
